// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.vi');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Thêm Chú Giải";
Blockly.Msg.AUTH = "Vui lòng cho phép ứng dụng được lưu dữ liệu của bạn và tự động chia sẻ bằng tên của bạn";
Blockly.Msg.CHANGE_VALUE_TITLE = "Thay giá trị thành:";
Blockly.Msg.CHAT = "Trò chuyện với cộng tác viên của bạn bằng cách gõ vào hộp này!";
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Thu Nhỏ Mọi Mảnh";
Blockly.Msg.COLLAPSE_BLOCK = "Thu Nhỏ Mảnh";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "màu 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "màu 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "tỉ lệ";
Blockly.Msg.COLOUR_BLEND_TITLE = "pha";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Pha hai màu với nhau theo tỉ lệ (0 - 100).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://vi.wikipedia.org/wiki/M%C3%A0u_s%E1%BA%AFc";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Chọn một màu từ bảng màu.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "màu bất kỳ";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "chọn một màu bất kỳ.";
Blockly.Msg.COLOUR_RGB_BLUE = "màu xanh dương";
Blockly.Msg.COLOUR_RGB_GREEN = "màu xanh lá cây";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "màu đỏ";
Blockly.Msg.COLOUR_RGB_TITLE = "Tạo màu từ";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Tạo màu từ ba màu: đỏ, xanh lá cây, xanh dương với số lượng cụ thể.  Mỗi số phải có giá trị từ 0 đến 100.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "thoát";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "sang lần lặp tiếp theo";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Thoát khỏi vòng lặp hiện tại.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Bỏ qua phần còn lại trong vòng lặp này, và sang lần lặp tiếp theo.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Chú ý: Mảnh này chỉ có thế dùng trong các vòng lặp.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "với mỗi thành phần %1 trong danh sách %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Trong một danh sách, lấy từng thành phần, gán vào biến \"%1\", rồi thực hiện một số lệnh.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "đếm theo %1 từ %2 đến %3 mỗi lần thêm %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Đếm từ số đầu đến số cuối. Khi đến mỗi số, gán số vào biến \"%1\" rồi thực hiện các lệnh.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Thêm một điều kiện vào mảnh nếu.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Cuối cùng, khi không điều kiện nào đúng.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Thêm, bỏ, hoặc đổi thứ tự các mảnh con để tạo cấu trúc mới cho mảnh nếu.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "nếu không";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "nếu không nếu";
Blockly.Msg.CONTROLS_IF_MSG_IF = "nếu";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Nếu điều kiện đúng, thực hiện các lệnh.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Nếu điều kiện đúng, thực hiện các lệnh đầu.  Nếu sai, thực hiện các lệnh sau.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Nếu điều kiện đúng, thực hiện các lệnh đầu.  Nếu không, nếu điều kiện thứ hai đúng, thực hiện các lệnh thứ hai.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Nếu điều kiện đúng, thực hiện các lệnh đầu.  Nếu không, nếu điều kiện thứ hai đúng, thực hiện các lệnh thứ hai.  Nếu không điều kiện nào đúng, thực hiện các lệnh cuối cùng.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "thực hiện";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "lặp lại %1 lần";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Thực hiện các lệnh vài lần.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "lặp lại cho đến khi";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "lặp lại trong khi";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Miễn là điều kiện còn sai, thì thực hiện các lệnh.  Khi điều kiện đúng thì ngưng.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Miễn là điều kiện còn đúng, thì thực hiện các lệnh.";
Blockly.Msg.DELETE_ALL_BLOCKS = "Xóa hết %1 mảnh?";
Blockly.Msg.DELETE_BLOCK = "Xóa Mảnh Này";
Blockly.Msg.DELETE_X_BLOCKS = "Xóa %1 Mảnh";
Blockly.Msg.DISABLE_BLOCK = "Ngưng Tác Dụng";
Blockly.Msg.DUPLICATE_BLOCK = "Tạo Bản Sao";
Blockly.Msg.ENABLE_BLOCK = "Phục Hồi Tác Dụng";
Blockly.Msg.EXPAND_ALL = "Mở Lớn Mọi Mảnh";
Blockly.Msg.EXPAND_BLOCK = "Mở Lớn Mảnh";
Blockly.Msg.EXTERNAL_INPUTS = "Chỗ Gắn Bên Ngoài";
Blockly.Msg.HELP = "Trợ Giúp";
Blockly.Msg.INLINE_INPUTS = "Chỗ Gắn Cùng Dòng";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "tạo danh sách trống";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "trả lại một danh sách, với độ dài 0, không có thành tố nào cả";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "danh sách";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Thêm, bỏ, hoặc sắp xếp lại các thành phần để tạo dựng mảnh danh sách này.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "tạo danh sách gồm";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Thêm vật vào danh sách.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Tạo một danh sách bao gồm nhiều vậts, với một số lượng bất kỳ.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "đầu tiên";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "(đếm từ cuối) thứ";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "thứ";
Blockly.Msg.LISTS_GET_INDEX_GET = "lấy thành tố";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "lấy và xóa thành tố";
Blockly.Msg.LISTS_GET_INDEX_LAST = "cuối cùng";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "bất kỳ";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "xóa thành tố";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "trả lại thành tố đầu tiên trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "trả lại thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố cuối cùng.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "trả lại thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố đầu tiên.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "trả lại thành tố cuối cùng trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "trả lại một thành tố bất kỳ trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "trả lại và xóa thành tố đầu tiên trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "trả lại và xóa thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố cuối cùng.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "trả lại và xóa thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố đầu tiên.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "trả lại và xóa thành tố cuối cùng trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "trả lại và xóa mộtthành tố bất kỳ trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Xóa thành tố đầu tiên trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Xóa thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố cuối cùng.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Xóa thành tố trong danh sách ở vị trí ấn định.  Số 1 là thành tố đầu tiên.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Xóa thành tố cuối cùng trong danh sách.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Xóa thành tố bất kỳ trong danh sách.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "đến (đếm từ cuối) thứ";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "đến thứ";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "đến cuối cùng";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "lấy một danh sách con từ đầu tiên";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "lấy một danh sách con từ (đếm từ cuối) thứ";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "lấy một danh sách con từ thứ";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Lấy một mảng của danh sách này để tạo danh sách con.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "tìm sự có mặt đầu tiên của vật";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "tìm sự có mặt cuối cùng của vật";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "trả lại vị trí xuất hiện đầu/cuối của vật trong danh sách.  Nếu không tìm thấy thì trả lại số 0.";
Blockly.Msg.LISTS_INLIST = "trong dánh sách";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 trống rỗng";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "trả lại “đúng\" nếu danh sách không có thành tử nào.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "độ dài của %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "trả lại độ dài của một danh sách.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "tạo danh sách gồm một vật %1 lặp lại %2 lần";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Tạo danh sách gồm một số lượng vật nhất định với mỗi vật đều giống nhau.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "giá trị";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "gắn chèn vào vị trí";
Blockly.Msg.LISTS_SET_INDEX_SET = "đặt thành tố";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Gắn chèn vật vào đầu danh sách.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Gắn chèn vật vào danh sách theo vị trí ấn định từ phía cuối.  #1 là thành tố cuối cùng.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Gắn chèn vật vào danh sách theo vị trí ấn định.  #1 là thành tố đầu tiên.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Gắn thêm vật vào cuối danh sách.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Gắn chèn vật vào danh sách ở vị trí ngẫu nhiên.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Đặt giá trị của thành tố đầu tiên trong danh sách.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Đặt giá trị của thành tố trong một danh sách ở vị trí ấn định từ phía cuối.  #1 là thành tố cuối cùng.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Đặt giá trị của thành tố ở vị trí ấn định trong một danh sách.  #1 là thành tố đầu tiên.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Đặt giá trị của thành tố cuối cùng trong danh sách.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Đặt giá trị của thành tố ngẫu nhiên trong danh sách.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "tăng dần";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "giảm dần";  // untranslated
Blockly.Msg.LISTS_SORT_TITLE = "sắp xếp %1 %2 %3";  // untranslated
Blockly.Msg.LISTS_SORT_TOOLTIP = "Sắp xếp một bản sao của một danh sách.";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabetic, ignore case";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "số";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "chữ cái";  // untranslated
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Ghép các đoạn văn bản thành 1 và phân cách bởi dấu phân cách.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Tách văn bản thành một danh sách các văn bản, ngắt ở mỗi dấu phân cách.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "với dấu phân cách";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "sai";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "trả lại \"đúng\" hoặc \"sai\".";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "đúng";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://vi.wikipedia.org/wiki/B%E1%BA%A5t_%C4%91%E1%BA%B3ng_th%E1%BB%A9c";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "trả lại giá trị \"đúng\" (true) nếu giá trị hai đầu vào bằng nhau.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "trả lại giá trị \"đúng\" (true) nếu đầu vào thứ nhất lớn hơn đầu vào thứ hai.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "trả lại giá trị \"đúng\" (true) nếu đầu vào thứ nhất lớn hơn hoặc bằng đầu vào thứ hai.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "trả lại giá trị \"đúng\" (true) nếu đầu vào thứ nhất nhỏ hơn đầu vào thứ hai.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "trả lại giá trị \"đúng\" (true) nếu đầu vào thứ nhất nhỏ hơn hoặc bằng đầu vào thứ hai.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "trả lại giá trị \"đúng\" (true) nếu giá trị hai đầu vào không bằng nhau.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "không %1";
Blockly.Msg.LOGIC_NEGATE_STR = "của chuỗi %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "trả lại \"đúng\" (true) nếu đầu vào sai.  trả lại \"sai\" (false) nếu đầu vào đúng.";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP_STR = "Trả lại giá trị theo vị trí của chuỗi dư liệu";
Blockly.Msg.VARIABLES_SET_TOOLTIP_STR = "Gán giá trị cho chuỗi dữ liệu"
Blockly.Msg.LOGIC_NULL = "trống không";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "trả lại trống không.";
Blockly.Msg.LOGIC_OPERATION_AND = "và";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "hoặc";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "trả lại \"đúng\" (true) nếu cả hai đầu vào đều đúng.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "trả lại \"đúng\" (true) nếu ít nhất một trong hai đầu vào đúng.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "kiểm tra";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "nếu sai";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "nếu đúng";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Kiểm tra điều kiện. Nếu điều kiện đúng, trả lại giá trị từ mệnh đề \"nếu đúng\" nếu không đúng, trả lại giá trị từ mệnh đề \"nếu sai\".";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://vi.wikipedia.org/wiki/S%E1%BB%91_h%E1%BB%8Dc";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "trả lại tổng của hai con số.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "trả lại thương của hai con số.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "trả lại hiệu của hai con số.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "trả lại tích của hai con số.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "trả lại số lũy thừa với số thứ nhất là cơ số và số thứ hai là số mũ.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://vi.wikipedia.org/wiki/Ph%C3%A9p_c%E1%BB%99ng";
Blockly.Msg.MATH_CHANGE_TITLE = "cộng vào %1 giá trị %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Cộng số đầu vào vào biến \"%1\".";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "trả lại các đẳng số thường gặp: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (vô cực).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "giới hạn %1 không dưới %2 không hơn %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Giới hạn số đầu vào để không dưới số thứ nhất và không hơn số thứ hai.";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "chia hết cho";
Blockly.Msg.MATH_IS_EVEN = "chẵn";
Blockly.Msg.MATH_IS_NEGATIVE = "là số âm";
Blockly.Msg.MATH_IS_ODD = "lẻ";
Blockly.Msg.MATH_IS_POSITIVE = "là số dương";
Blockly.Msg.MATH_IS_PRIME = "là số nguyên tố";
Blockly.Msg.MATH_IS_TOOLTIP = "Kiểm tra con số xem nó có phải là số chẵn, lẻ, nguyên tố, nguyên, dương, âm,  hay xem nó có chia hết cho số đầu vào hay không.  trả lại đúng hay sai.";
Blockly.Msg.MATH_IS_WHOLE = "là số nguyên";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "số dư của %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Chia số thứ nhất cho số thứ hai rồi trả lại số dư từ.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://vi.wikipedia.org/wiki/S%E1%BB%91";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Một con số.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "giá trị trung bình của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "số lớn nhât của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "số trung vị của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "số nhỏ nhất của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "các mode của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "một số bất kỳ của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "độ lệch chuẩn của một danh sách";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "tổng của một danh sách";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "trả lại giá trị trung bình từ của danh sách số.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "trả lại số lớn nhất trong tất cả các số trong danh sách.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "trả lại số trung vị của danh sách số.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "trả lại số nhỏ nhất trong tất cả các số trong danh sách.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "trả lại các số có mặt nhiều nhất trong danh sách.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "trả lại một số bất kỳ từ các số trong danh sách.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "trả lại độ lệch chuẩn của danh sách số.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "trả lại tổng số của tất cả các số trong danh sách.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "phân số bất kỳ";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "trả lại một phân số bất kỳ không nhỏ hơn 0.0 và không lớn hơn 1.0.";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "Một số nguyên bất kỳ từ %1 đến %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "trả lại một số nguyên bất kỳ lớn hơn hoặc bằng số đầu và nhỏ hơn hoặc bằng số sau.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "làm tròn";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "làm tròn xuống";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "làm tròn lên";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Làm tròn lên hoặc tròn xuống số đầu vào.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://vi.wikipedia.org/wiki/C%C4%83n_b%E1%BA%ADc_hai";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "giá trị tuyệt đối";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "căn bậc hai";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "trả lại giá trị tuyệt đối của số đầu vào.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "trả lại lũy thừa của số e với số mũ đầu vào.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "trả lại lôgarit tự nhiên của số đầu vào.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "trả lại lôgarit cơ số 10 của số đầu vào.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Đổi dấu của số đầu vào: âm thành dương và dương thành âm, và trả lại số mới.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "trả lại lũy thừa của số 10 với số mũ đầu vào.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "trả lại căn bật hai của số đầu vào.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://vi.wikipedia.org/wiki/H%C3%A0m_l%C6%B0%E1%BB%A3ng_gi%C3%A1c";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "trả lại Arccos của một góc (theo độ).";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "trả lại Arcsin của một góc (theo độ).";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "trả lại Arctang của một góc (theo độ).";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "trả lại Cos của một góc (theo độ).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "trả lại Sin của một góc (theo độ).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "trả lại Tang của một góc (theo độ).";
Blockly.Msg.ME = "Tôi";
Blockly.Msg.NEW_VARIABLE = "Biến mới...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Tên của biến mới:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "cho phép báo cáo";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "với:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Chạy một thủ tục không có giá trị trả lại.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Chạy một thủ tục có giá trị trả lại.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "với:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Tạo mảnh \"thực hiện %1\"";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Mô tả chức năng của hàm...";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "do something";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Một thủ tục không có giá trị trả lại.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "trả lại";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Một thủ tục có giá trị trả lại.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Chú ý: Thủ tục này có lặp lại tên các tham số.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Làm nổi bật thủ tục";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Khi điều kiện đúng thì trả lại một giá trị.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Chú ý: Mảnh này chỉ có thể dùng trong một thủ tục.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "biến:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Thêm một đầu vào cho hàm.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "các tham số";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Thêm, xóa hoặc sắp xếp lại các đầu vào cho hàm này.";
Blockly.Msg.REDO = "Quay lại";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Xóa Chú Giải";
Blockly.Msg.RENAME_VARIABLE = "Thay tên biến...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Thay tên tất cả \"%1\" biến này thành:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "thêm văn bản";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "ở cuối";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Thêm một mảng văn bản vào biến \"%1\".";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "thành chữ thường";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "thành Chữ In Đầu Mỗi Từ";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "thành CHỮ IN HOA";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "trả lại văn bản sau khi chuyển đổi chữ in hoa hay thường.";
Blockly.Msg.TEXT_CHARAT_FIRST = "lấy ký tự đầu tiên";
Blockly.Msg.TEXT_CHARAT_FROM_END = "lấy từ phía cuối, ký tự thứ";
Blockly.Msg.TEXT_CHARAT_FROM_START = "lấy ký tự thứ";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "trong văn bản";
Blockly.Msg.TEXT_CHARAT_LAST = "lấy ký tự cuối cùng";
Blockly.Msg.TEXT_CHARAT_RANDOM = "lấy ký tự bất kỳ";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "trả lại ký tự ở vị trí đặt ra.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "thêm vật mới vào văn bản.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "kết nối";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Thêm, bỏ, hoặc sắp xếp lại các thành phần để tạo dựng mảnh văn bản này.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "đến từ phía cuối, ký tự thứ";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "đến ký tự thứ";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "đến ký tự cuối cùng";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "trong văn bản";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "lấy từ ký tự đầu tiên";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "lấy từ phía cuối, ký tự thứ";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "lấy từ ký tự thứ";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "trả lại một mảng ký tự ấn định từ trong văn bản.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "trong văn bản";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "tìm sự có mặt đầu tiên của";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "tìm sự có mặt cuối cùng của";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "trả lại vị trí xuất hiện đầu/cuối của văn bản thứ nhất trong văn bản thứ hai.  Nếu không tìm thấy thì trả lại số 0.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 trống không";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "trả lại “đúng nếu văn bản không có ký tự nào.";
Blockly.Msg.TEXT_JOIN_HELPURL = '';
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "tạo văn bản từ";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Tạo một văn bản từ các thành phần.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "độ dài của %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "trả lại số lượng ký tự (kể cả khoảng trắng) trong văn bản đầu vào.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "in lên màng hình %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "In ra màng hình một văn bản, con số, hay một giá trị đầu vào khác.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "nhập vào vào một con số.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "nhập vào vào một văn bản.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "nhập vào vào con số với dòng hướng dẫn";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "nhập vào vào văn bản với dòng hướng dẫn";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/string_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Một ký tự, một từ, hay một dòng.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "cắt các không gian từ cả hai mặt của";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "cắt các không gian từ bên trái của";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "cắt các không gian từ bên phải của";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "trả lại bản sao của văn bản sau khi xóa khoảng trắng từ một hoặc hai bên.";
Blockly.Msg.TODAY = "Hôm nay";  // untranslated
Blockly.Msg.UNDO = "Quay trở lại";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "item";
Blockly.Msg.VARIABLES_DEFAULT_STR_NAME = "buff";
Blockly.Msg.variables_str_name = "Vị trí";
Blockly.Msg.variables_str_add = "của chuỗi";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Tạo mảnh \"đặt vào %1\"";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "trả lại giá trị của.";
Blockly.Msg.VARIABLES_SET = "cho %1 bằng %2";
Blockly.Msg.VARIABLES_STR = "Cho chuỗi %1 bằng %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Tạo mảnh \"lấy %1\"";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Đặt giá trị của biến này thành...";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

// Ardublockly strings
Blockly.Msg.ARD_ANALOGREAD = "Đọc tín hiệu Tương Tự tại chân ";  // untranslated
Blockly.Msg.ARD_ANALOGREAD_TIP = "Trả về giá trị giữa 0 và 1024";  // untranslated
Blockly.Msg.ARD_ANALOGWRITE = "Xuất tín hiệu Tương Tự tại chân";  // untranslated
Blockly.Msg.ARD_ANALOGWRITE_TIP = "Ghi giá trị Tương Tự trong khoảng từ 0 đến 255 vào một Cổng PWM";  // untranslated
Blockly.Msg.ARD_BUILTIN_LED = "Thiết lập đèn LED tích hợp";  // untranslated
Blockly.Msg.ARD_BUILTIN_LED_TIP = "Bật hoặc tắt đèn LED tích hợp của Arduino";  // untranslated
Blockly.Msg.ARD_COMPONENT_WARN1 = "Phải thêm khối cấu hình % 1 có cùng tên % 2 để sử dụng khối này!";  // untranslated
Blockly.Msg.ARD_DEFINE = "Định nghĩa";  // untranslated
Blockly.Msg.ARD_DIGITALREAD = "Đọc tín hiệu Số tại chân";  // untranslated
Blockly.Msg.ARD_DIGITALREAD_TIP = "Đọc tín hiệu Số của 1 chân: Cao or Thấp";  // untranslated
Blockly.Msg.ARD_DIGITALWRITE = "Xuất tín hiệu Số cho chân ";  // untranslated
Blockly.Msg.ARD_DIGITALWRITE_TIP = "Ghi giá trị Cao hoặc Thấp cho cổng chỉ định";  // untranslated
Blockly.Msg.ARD_FUN_RUN_LOOP = "Lặp lại mãi mãi:";  // untranslated
Blockly.Msg.ARD_FUN_RUN_SETUP = "Cài đặt ban đầu:";  // untranslated
Blockly.Msg.ARD_FUN_RUN_TIP = "Xác định các hàm setup () và loop () cho Arduino.";  // untranslated
Blockly.Msg.ARD_HIGH = "CAO";  // untranslated
Blockly.Msg.ARD_HIGHLOW_TIP = "Đặt trạng thái logic 1 chân Cao hoặc Thấp.";  // untranslated
Blockly.Msg.ARD_LOW = "THẤP";  // untranslated
Blockly.Msg.ARD_MAP = "Ánh xạ";  // untranslated
Blockly.Msg.ARD_MAP_TIP = "Ánh xạ lại một số từ [0-1024] sang số khác.";  // untranslated
Blockly.Msg.ARD_MAP_VAL = "Giá trị từ[0-";  // untranslated
Blockly.Msg.ARD_NOTONE = "Tắt âm thanh trên chân#";  // untranslated
Blockly.Msg.ARD_NOTONE_PIN = "Không có âm thanh trên chân#";  // untranslated
Blockly.Msg.ARD_NOTONE_PIN_TIP = "Dừng tạo âm trên chân";  // untranslated
Blockly.Msg.ARD_NOTONE_TIP = "Tắt âm báo trên chân đã chọn";  // untranslated
Blockly.Msg.ARD_PIN_WARN1 = "Pin %1 is needed for %2 as pin %3. Already used as %4.";  // untranslated
Blockly.Msg.ARD_PULSETIMEOUT_TIP = "Đo thời lượng của một xung trên chân được chọn, nếu nó ở trong khoảng thời gian chờ tính bằng micrô giây.";  // untranslated
Blockly.Msg.ARD_PULSE_READ = "Đo thời lượng xung %1 trên chân %2";  // untranslated
Blockly.Msg.ARD_PULSE_READ_TIMEOUT = "Đo thời lượng xung %1 trên chân %2 thời gian chờ %3 μs";  // untranslated
Blockly.Msg.ARD_PULSE_TIP = "Đo khoảng thời gian mức cao trên chân.";  // untranslated
Blockly.Msg.ARD_SERIAL_BPS = "bps";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT = "in ra";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "Thêm dòng mới";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_TIP = "In dữ liệu lên bàn điều khiển / cổng nối tiếp dưới dạng văn bản ASCII có thể đọc được.";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_WARN = "Phải thiết lập khối thiết lập cho %1 vào không gian làm việc để sử dụng khối này!";  // untranslated
Blockly.Msg.ARD_SERIAL_SETUP = "Cài đặt";  // untranslated
Blockly.Msg.ARD_SERIAL_SETUP_TIP = "Chọn tốc độ cho cổng nối tiếp";  // untranslated
Blockly.Msg.ARD_SERIAL_SPEED = ":  đến tốc độ";  // untranslated
Blockly.Msg.ARD_SERVO_READ = "Đọc SERVO tại chân#";  // untranslated
Blockly.Msg.ARD_SERVO_READ_TIP = "Đọc góc Servo";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE = "Thiết lập SERVO tại chân";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "Độ (0~180)";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_TIP = "Thiết lập Servo tại góc chỉ định.";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_TO = "tới";  // untranslated
Blockly.Msg.ARD_SETTONE = "Bật âm thanh chân#";  // untranslated
Blockly.Msg.ARD_SPI_SETUP = "Thiết lập";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_CONF = "Cấu hình:";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "Phân chia đồng hồ";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE = "Chế độ SPI (idle - edge)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Thấp - Cạnh xuống)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Thấp - Cạnh lên)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (Cao - Cạnh xuống)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (Cao - Cạnh lên)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_SHIFT = "dịch dữ liệu";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_TIP = "Cấu hình SPI.";  // untranslated
Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "Gửi tin nhắn SPI đến một thiết bị khách được chỉ định và lấy lại dữ liệu.";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_NONE = "không có";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_SLAVE = "tới thiết bị khách chân";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_TIP = "Gửi tin nhắn SPI đến một thiết bị khách được chỉ định.";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_VAL = "chuyển đổi";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_WARN1 = "Phải thiết lập khối  %1 vào không gian làm việc để sử dụng khối này!";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_WARN2 = "Giá trị cũ của chân %1 không còn nữa.";  // untranslated
Blockly.Msg.ARD_STEPPER_COMPONENT = "bước";  // untranslated
Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper";  // untranslated
Blockly.Msg.ARD_STEPPER_FOUR_PINS = "4";  // untranslated
Blockly.Msg.ARD_STEPPER_MOTOR = "Động cơ bước:";  // untranslated
Blockly.Msg.ARD_STEPPER_NUMBER_OF_PINS = " Số lượng chân";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN1 = "chân1#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN2 = "chân2#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN3 = "chân3#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN4 = "chân4#";  // untranslated
Blockly.Msg.ARD_STEPPER_REVOLVS = "Có bao nhiêu bước trong 1 vòng quay.";  // untranslated
Blockly.Msg.ARD_STEPPER_SETUP = "Thiết lập động cơ bước";  // untranslated
Blockly.Msg.ARD_STEPPER_SETUP_TIP = "cấu hình chân ra động cơ bước và các cài đặt khác.";  // untranslated
Blockly.Msg.ARD_STEPPER_SPEED = "Thiết lập tốc độ (rpm)";  // untranslated
Blockly.Msg.ARD_STEPPER_STEP = "di chuyển bước";  // untranslated
Blockly.Msg.ARD_STEPPER_STEPS = "các bước";  // untranslated
Blockly.Msg.ARD_STEPPER_STEP_TIP = "Quay số bước chỉ định.";  // untranslated
Blockly.Msg.ARD_STEPPER_TWO_PINS = "2";  // untranslated
Blockly.Msg.ARD_TIME_DELAY = "chờ";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_MICROS = "micros giây";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "Đợi thời gian cụ thể tính bằng micros giây";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_TIP = "Đợi thời gian cụ thể tính bằng micros giây";  // untranslated
Blockly.Msg.ARD_TIME_INF = "chờ mãi (kết thúc chương trình)";  // untranslated
Blockly.Msg.ARD_TIME_INF_TIP = "Chờ đợi vô thời hạn, dừng chương trình.";  // untranslated
Blockly.Msg.ARD_TIME_MICROS = "Thời gian trôi qua (micro giây)";  // untranslated
Blockly.Msg.ARD_TIME_MICROS_TIP = "Trả về số lượng micro giây kể từ khi bo mạch Arduino bắt đầu chạy chương trình hiện tại. Phải được lưu trữ trong một số nguyên dài dương";  // untranslated
Blockly.Msg.ARD_TIME_MILLIS = "Thời gian trôi qua (mili giây)";  // untranslated
Blockly.Msg.ARD_TIME_MILLIS_TIP = "Trả về số mili giây kể từ khi bo mạch Arduino bắt đầu chạy chương trình hiện tại. Phải được lưu trữ trong một số nguyên dài dương";  // untranslated
Blockly.Msg.ARD_TIME_MS = "mili giây ";  // untranslated
Blockly.Msg.ARD_TONEFREQ = "ở tần số";  // untranslated
Blockly.Msg.ARD_TONE_FREQ = "tần số";  // untranslated
Blockly.Msg.ARD_TONE_PIN = "Âm thanh ở chân#";  // untranslated
Blockly.Msg.ARD_TONE_PIN_TIP = "Tạo âm thanh trên chân";  // untranslated
Blockly.Msg.ARD_TONE_TIP = "Đặt âm trên chân theo tần số được chỉ định trong phạm vi 31 - 65535";  // untranslated
Blockly.Msg.ARD_TONE_WARNING = "Tần số phải nằm trong phạm vi 31 - 65535";  // untranslated
Blockly.Msg.ARD_TYPE_ARRAY = "Mảng";  // untranslated
Blockly.Msg.ARD_TYPE_BOOL = "Boolean";  // untranslated
Blockly.Msg.ARD_TYPE_CHAR = "Kí tự";  // untranslated
Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "Thiếu khối";  // untranslated
Blockly.Msg.ARD_TYPE_DECIMAL = "Số thập phân";  // untranslated
Blockly.Msg.ARD_TYPE_LONG = "Số lượng lớn";  // untranslated
Blockly.Msg.ARD_TYPE_NULL = "Không có giá trị";  // untranslated
Blockly.Msg.ARD_TYPE_NUMBER = "Số";  // untranslated
Blockly.Msg.ARD_TYPE_SHORT = "Số ngắn";  // untranslated
Blockly.Msg.ARD_TYPE_TEXT = "Văn bản";  // untranslated
Blockly.Msg.ARD_TYPE_UNDEF = "Chưa xác định";  // untranslated
Blockly.Msg.ARD_VAR_AS = "dạng";  // untranslated
Blockly.Msg.ARD_VAR_AS_TIP = "Đặt giá trị cho một loại cụ thể";  // untranslated
Blockly.Msg.ARD_WRITE_TO = "đến";  // untranslated
Blockly.Msg.NEW_INSTANCE = "Ví dụ...";  // untranslated
Blockly.Msg.NEW_INSTANCE_TITLE = "Tên ví dụ:";  // untranslated
Blockly.Msg.RENAME_INSTANCE = "Đổi tên ví dụ...";  // untranslated
Blockly.Msg.RENAME_INSTANCE_TITLE = "Đổi tên tất cả ví dụ '%1' thành:";  // untranslated


Blockly.Msg.robocarv2 = "Khi KC-Bot khởi động";
Blockly.Msg.kcbot_motor_motor = "Cài đặt động cơ";
Blockly.Msg.kcbot_motor_speed = "tốc độ";
Blockly.Msg.kcbot_ledrgb = "Cài đặt đèn LED";
Blockly.Msg.kcbot_ledrgb_red = "đỏ";
Blockly.Msg.kcbot_ledrgb_green = "xanh lá cây";
Blockly.Msg.kcbot_ledrgb_blue = "xanh nước biển";
Blockly.Msg.kcbot_servo_setup = "Cài đặt servo";
Blockly.Msg.kcbot_servo_angle = "độ";
Blockly.Msg.kcbot_tone_note = "Phát nhạc nốt";
Blockly.Msg.kcbot_tone = "nhịp";
Blockly.Msg.kcbot_lcd_display = "LCD hiển thị chữ";
Blockly.Msg.kcbot_lcd_pos = "vị trí";
Blockly.Msg.kcbot_lcd_clear = "Xóa màn hình";
Blockly.Msg.kcbot_rtc_set_time = "Cài đặt thời gian";
Blockly.Msg.kcbot_rtc_set_time_dayofweek = "ngày trong tuần";
Blockly.Msg.kcbot_rtc_set_time_mon = "Thứ 2";
Blockly.Msg.kcbot_rtc_set_time_tues = "Thứ 3";
Blockly.Msg.kcbot_rtc_set_time_wed = "Thứ tư";
Blockly.Msg.kcbot_rtc_set_time_thur = "Thứ 5";
Blockly.Msg.kcbot_rtc_set_time_fri = "Thứ 6";
Blockly.Msg.kcbot_rtc_set_time_sat = "Thứ 7";
Blockly.Msg.kcbot_rtc_set_time_sun = "Chủ nhật";
Blockly.Msg.kcbot_rtc_update = "Cập nhật thời gian";
Blockly.Msg.kcbot_rtc_read_time = "Đọc giờ";
Blockly.Msg.kcbot_rtc_read_date = "Đọc ngày tháng rtc";
Blockly.Msg.kcbot_readlm35 = "Đọc nhiệt độ (LM35)";
Blockly.Msg.kcbot_dht11_temp = "Đọc nhiệt độ (DHT11)";
Blockly.Msg.kcbot_dht11_humi = "Đọc độ ẩm (DHT11)";
Blockly.Msg.kcbot_ultrasonic = "Đọc khoảng cách";
Blockly.Msg.kcbot_rtc_read = "Đọc thời gian rtc";
Blockly.Msg.kcbot_rtc_read_hour = "Giờ";
Blockly.Msg.kcbot_rtc_read_min = "Phút";
Blockly.Msg.kcbot_rtc_read_sec = "Giây";
Blockly.Msg.kcbot_rtc_read_dayofweek = "Thứ";
Blockly.Msg.kcbot_rtc_read_date = "Ngày";
Blockly.Msg.kcbot_rtc_read_month = "Tháng";
Blockly.Msg.kcbot_rtc_read_year = "Năm";
Blockly.Msg.loop_forever = "Lặp lại mãi mãi";
Blockly.Msg.loop_forever_do = "Thực hiện";
Blockly.Msg.ARD_nhietdo = "Đọc giá trị nhiệt độ tại chân";
Blockly.Msg.kcbot_sotrungvi = "Tính giá trị trung vị với giá trị Tương Tự";
Blockly.Msg.kcbot_123 = "Kết nối Wifi tên";
Blockly.Msg.kcbot_mat = "mật khẩu";
Blockly.Msg.kcbot_api = "Gửi dữ liệu";
Blockly.Msg.kcbot_run = "với nguồn";
Blockly.Msg.kcbot_run_stop = "Dừng lại";
Blockly.Msg.kcbot_run_forward = "Tiến lên";
Blockly.Msg.kcbot_run_back = "Lùi lại";
Blockly.Msg.kcbot_run_left = "Quay trái";
Blockly.Msg.kcbot_run_right = "Quay phải";
Blockly.Msg.kcbot_run_forward_at_sec = "trong";
Blockly.Msg.sec = "giây";
Blockly.Msg.kcbot_stop_moving = "Dừng di chuyển";
Blockly.Msg.kcbot_ultrasonic_trig = "Đọc khoảng cách chân phát";
Blockly.Msg.kcbot_ultrasonic_echo = "chân nhận";
Blockly.Msg.kcbot_getIr = "Kênh";
Blockly.Msg.kcbot_getIr_key = "phím";
Blockly.Msg.kcbot_getIr_key_go = "Lên";
Blockly.Msg.kcbot_getIr_key_back = "xuống";
Blockly.Msg.kcbot_getIr_key_left = "trái";
Blockly.Msg.kcbot_getIr_key_right = "phải";
Blockly.Msg.kcbot_getIr_key_f2 = "F2";
Blockly.Msg.kcbot_getIr_key_f4 = "F4";
Blockly.Msg.kcbot_getIr_key_f6 = "F6";
Blockly.Msg.kcbot_getIr_k1 = "K1";
Blockly.Msg.kcbot_getIr_k2 = "K2";
Blockly.Msg.kcbot_getIr_k3 = "K3";
Blockly.Msg.kcbot_getIr_k4 = "K4";
Blockly.Msg.kcbot_getIr_k5 = "K5";
Blockly.Msg.kcbot_getIr_k6 = "K6";
Blockly.Msg.kcbot_getIr_k7 = "K7";
Blockly.Msg.kcbot_getIr_k8 = "K8";
Blockly.Msg.kcbot_Serial_read = "Đọc dữ liệu";
Blockly.Msg.kcbot_read_data_ir = "Đọc tín hiệu IR tại chân";
Blockly.Msg.kcbot_Write = " với WirteAPIKey";
Blockly.Msg.kcbot_bang = "lên biểu đồ";

Blockly.Msg.kcbot_readDS18b20 = "Đọc nhiệt độ (ds18b20)";



Blockly.Msg.kcbot_read_Doam = "Đọc độ ẩm đất";
Blockly.Msg.kcbot_textbien_ch = "Cho biến";
Blockly.Msg.kcbot_textbien_ba = "của hàm bằng";
Blockly.Msg.kcbot_trans_name = "Tên điểm phát sóng wifi";
Blockly.Msg.kcbot_trans_pass = "mật khẩu";
Blockly.Msg.kcbot_Blynk_Api = "Địa chỉ kết nối Blynk";
Blockly.Msg.kcbot_Blynk_Name = "tên wifi";
Blockly.Msg.kcbot_Blynk_Pass = "Mật khẩu";
Blockly.Msg.kcbot_phenikee_id = "Điều khiển bánh omni với địa chỉ";
Blockly.Msg.kcbot_phenikee_tien = "chiều";
Blockly.Msg.kcbot_phenikee_speed = "tốc độ";
Blockly.Msg.Arduino_robot_motor = "Cài đặt động cơ";
Blockly.Msg.Arduino_robot_motor_ch = "quay";
Blockly.Msg.Arduino_robot_motor_up = "tiến";
Blockly.Msg.Arduino_robot_motor_down = "lùi";
Blockly.Msg.Arduino_robot_motor_stop = "dừng";
Blockly.Msg.Arduino_robot_run = "Arduino robot";
Blockly.Msg.Arduino_robot = "Khi Arduino robot khởi động";
Blockly.Msg.Arduino = "Khi Arduino khởi động";
Blockly.Msg.Mbot_robot = "Khi Mbot khởi động";
Blockly.Msg.Mbot_motor_motor = "Cài đặt động cơ";
Blockly.Msg.Mbot_motor_speed = "Tốc độ";
Blockly.Msg.Mbot_port_1 = "cổng 1";
Blockly.Msg.Mbot_port_2 = "cổng 2";
Blockly.Msg.Mbot_port_3 = "cổng 3";
Blockly.Msg.Mbot_port_4 = "cổng 4";
Blockly.Msg.bluetooth_setup = "Phát bluetooth với tên: ";
Blockly.Msg.bluetooth_read = "Đọc dữ liệu nhận từ Bluetooth";
Blockly.Msg.ARD_bluetooth_write = "Gửi dữ liệu";
Blockly.Msg.ARD_bluetooth = "qua bluetooth";
Blockly.Msg.Python_run_out_put = "Cài đặt chân";
Blockly.Msg.Python_run_out = "mức";
Blockly.Msg.Python_run_out_put_high = "Cao";
Blockly.Msg.Python_run_out_put_low = "Thấp";
Blockly.Msg.Python_pwm_out_put = "Cài đặt PWM chân";
Blockly.Msg.Python_pwm_out = "đến";
Blockly.Msg.Python_digital_read = "Đọc giá trị số chân";
Blockly.Msg.Python_analog_read = "Đọc giá trị tương tự chân";
Blockly.Msg.kcbot_Python_servo = "quay góc";
Blockly.Msg.python_robot = "Khi Python robot khởi động";
Blockly.Msg.Python_start = "Bắt đầu";
Blockly.Msg.kcbot_lcd_dia_chi = "Địa chỉ";

// ---------------------------------------Airsense----------------------------------------
Blockly.Msg.AirsenseReadDataBME280 = "Đọc dữ liệu (BME280)";
Blockly.Msg.freeRTOS = "Tạo nhiệm vụ";
Blockly.Msg.AirsenseReadDataPMS7003 = "Đọc dữ liệu từ cảm biến (PMS7003)" ;
Blockly.Msg.ESP32_wifi = "Kết nối wifi";
Blockly.Msg.AirsenseReadDataMHZ14A  =  "Đọc dữ liệu từ cảm biến (MHZ14A)";
Blockly.Msg.SetDateDS3231="Nhập ngày, tháng, năm : "
Blockly.Msg.SetTimeDS3231="Nhập thời gian : "
Blockly.Msg.GetDateTimeDS3231="Ngày - giờ hiện tại"
Blockly.Msg.ConnectMQTT="Kết nối MQTT Client"